set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_1]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_2]
set_property IOSTANDARD LVCMOS33 [get_ports pmod_4]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PACKAGE_PIN A14 [get_ports pmod_1]
set_property PACKAGE_PIN A16 [get_ports pmod_2]
set_property PACKAGE_PIN B16 [get_ports pmod_4]
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U18 [get_ports rst]
