//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 13 2022 15:28:16
//
//      Input file      : 
//      Component name  : address_generator
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Address_Generator(CLK25, enable, rez_160x120, rez_320x240, vsync, address);
   input         CLK25;
   input         enable;
   input         rez_160x120;
   input         rez_320x240;
   input         vsync;
   output [18:0] address;
   
   reg [18:0]    val;
   assign address = val;
   
   
   always @(posedge CLK25)
      
      begin
         if (enable == 1'b1)
         begin
            if (rez_160x120 == 1'b1)
            begin
               if (val < 160 * 120)
                  val <= val + 1;
            end
            else if (rez_320x240 == 1'b1)
            begin
               if (val < 320 * 240)
                  val <= val + 1;
            end
            else
               if (val < 640 * 480)
                  val <= val + 1;
         end
         if (vsync == 1'b0)
            val <= {19{1'b0}};
      end
   
endmodule
