//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 13 2022 14:55:47
//
//      Input file      : 
//      Component name  : clocking
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module clocking(CLK_100, CLK_50, CLK_25);
   input       CLK_100;
   output      CLK_50;
   output      CLK_25;
   
   wire        clkin1;
   wire        clkfbout;
   wire        clkfbout_buf;
   wire        clkfboutb_unused;
   wire        clkout0;
   wire        clkout0b_unused;
   wire        clkout1;
   wire        clkout1b_unused;
   wire        clkout2_unused;
   wire        clkout2b_unused;
   wire        clkout3_unused;
   wire        clkout3b_unused;
   wire        clkout4_unused;
   wire        clkout5_unused;
   wire        clkout6_unused;
   wire [15:0] do_unused;
   wire        drdy_unused;
   wire        psdone_unused;
   wire        locked_unused;
   wire        clkfbstopped_unused;
   wire        clkinstopped_unused;
   
   
   IBUFG clkin1_buf(.O(clkin1), .I(CLK_100));
   
   
   MMCME2_ADV #("OPTIMIZED", 1'b0, "ZHOLD", 1'b0, 1, 10.000, 0.000, 1'b0, 20.000, 0.000, 0.500, 1'b0, 40, 0.000, 0.500, 1'b0, 10.000, 0.010) mmcm_adv_inst(.CLKFBOUT(clkfbout), .CLKFBOUTB(clkfboutb_unused), .CLKOUT0(clkout0), .CLKOUT0B(clkout0b_unused), .CLKOUT1(clkout1), .CLKOUT1B(clkout1b_unused), .CLKOUT2(clkout2_unused), .CLKOUT2B(clkout2b_unused), .CLKOUT3(clkout3_unused), .CLKOUT3B(clkout3b_unused), .CLKOUT4(clkout4_unused), .CLKOUT5(clkout5_unused), .CLKOUT6(clkout6_unused), .CLKFBIN(clkfbout_buf), .CLKIN1(clkin1), .CLKIN2(1'b0), .CLKINSEL(1'b1), .DADDR(1'b0), .DCLK(1'b0), .DEN(1'b0), .DI(1'b0), .DO(do_unused), .DRDY(drdy_unused), .DWE(1'b0), .PSCLK(1'b0), .PSEN(1'b0), .PSINCDEC(1'b0), .PSDONE(psdone_unused), .LOCKED(locked_unused), .CLKINSTOPPED(clkinstopped_unused), .CLKFBSTOPPED(clkfbstopped_unused), .PWRDWN(1'b0), .RST(1'b0));
   
   
   BUFG clkf_buf(.O(clkfbout_buf), .I(clkfbout));
   
   
   BUFG clkout1_buf(.O(CLK_50), .I(clkout0));
   
   
   BUFG clkout2_buf(.O(CLK_25), .I(clkout1));
   
endmodule
