//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 13 2022 14:57:52
//
//      Input file      : 
//      Component name  : rgb
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module RGB(Din, Nblank, R, G, B);
   input [11:0] Din;
   input        Nblank;
   output [7:0] R;
   output [7:0] G;
   output [7:0] B;
   
   
   assign R = (Nblank == 1'b1) ? {Din[11:8], Din[11:8]} : 
              8'b00000000;
   assign G = (Nblank == 1'b1) ? {Din[7:4], Din[7:4]} : 
              8'b00000000;
   assign B = (Nblank == 1'b1) ? {Din[3:0], Din[3:0]} : 
              8'b00000000;
   
endmodule

