webtalk_init -webtalk_dir C:/home/github/LogicDesign/Lab5-Advanced/Problem_3_4/Problem_3_4.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Booth_Multiplier_4bit_t_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 24 14:10:18 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e79f0e54-08b8-4637-a40a-8bc8954622b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7183aaedffdc413391b369c98ca7c04b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "72" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2370 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "72 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "30" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "56512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3547243487 -regid "" -xml C:/home/github/LogicDesign/Lab5-Advanced/Problem_3_4/Problem_3_4.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Booth_Multiplier_4bit_t_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/home/github/LogicDesign/Lab5-Advanced/Problem_3_4/Problem_3_4.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Booth_Multiplier_4bit_t_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/home/github/LogicDesign/Lab5-Advanced/Problem_3_4/Problem_3_4.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Booth_Multiplier_4bit_t_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
