webtalk_init -webtalk_dir D:/LogicDesignExperiment/share_repo/Lab5-Advanced/Problem_1_2/Problem_1_2.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Traffic_Light_Controller_t_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 25 23:15:43 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4c88d73b-dc36-4f4f-9811-c13fb1e68dc7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2a0b3733979a4a7eb594634aeb7691a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "984 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1647430674 -regid "" -xml D:/LogicDesignExperiment/share_repo/Lab5-Advanced/Problem_1_2/Problem_1_2.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Traffic_Light_Controller_t_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/LogicDesignExperiment/share_repo/Lab5-Advanced/Problem_1_2/Problem_1_2.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Traffic_Light_Controller_t_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/LogicDesignExperiment/share_repo/Lab5-Advanced/Problem_1_2/Problem_1_2.sim/sim_1/behav/xsim/xsim.dir/Lab5_Team3_Traffic_Light_Controller_t_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
