# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/LogicDesignExperiment/final_project/camera_try/camera_try.srcs/sources_1/ip/frame_buffer_1/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LogicDesignExperiment/final_project/camera_try/camera_try.gen/sources_1/ip/frame_buffer_1/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/LogicDesignExperiment/final_project/camera_try/camera_try.srcs/sources_1/ip/frame_buffer_1/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LogicDesignExperiment/final_project/camera_try/camera_try.gen/sources_1/ip/frame_buffer_1/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
